[package]
name = "tlib_conf"
version = "0.1.0"
authors = ["tajoy <tj328111241@gmail.com>"]

[lib]
name = "tlib_conf"
path = "src/lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
tlib_core = { path = "../tlib-core" }